INSERT INTO PERMISSAO(DESCRICAO) VALUES('ROLE_ADMIN');
INSERT INTO PERMISSAO(DESCRICAO) VALUES('ROLE_USUARIO');

INSERT INTO USUARIO(NOME, LOGIN, SENHA, ATIVO) VALUES ('Administrador', 'admin', '$2a$10$QCyZ4FcQ2oyA.r2UY4iZu.wZ/KNUrKfiv8RzQUa7w6nLBllzfdljG', true);
INSERT INTO USUARIO(NOME, LOGIN, SENHA, ATIVO) VALUES ('Bruno Carvalho', 'bruno', '$2a$10$QCyZ4FcQ2oyA.r2UY4iZu.wZ/KNUrKfiv8RzQUa7w6nLBllzfdljG', true);

INSERT INTO USUARIO_PERMISSOES VALUES(1,1);
INSERT INTO USUARIO_PERMISSOES VALUES(1,2);
INSERT INTO USUARIO_PERMISSOES VALUES(2,2);