version: 2.0
jobs:
  build:
    docker:
      - image: maven:3.5.0-jdk-8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "pom.xml"}}
            - v1-dependencies
      - run: mvn dependency:go-offline
      - run: mvn verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths: ~/.m2
          key: v1-dependencies-{{checksum "pom.xml"}}
      - store_artifacts:
          path: target/ROOT.war